### ISSUE TITLE
Cannot use lakos with auto_route

### ISSUE THREAD

**Issue by MichalNemec** [OlegAlexander/lakos#18]
Could the restriction be loosened a bit? I'm trying to use lakos, but it's conflicting with the auto_route dependencies.

No versions of auto_route_generator match >10.0.1 <11.0.0 and auto_route_generator 10.0.1 depends on glob ^2.1.3, auto_route_generator ^10.0.1 requires glob ^2.1.3.
And because lakos >=2.0.4 depends on glob 2.1.2, auto_route_generator ^10.0.1 is incompatible with lakos >=2.0.4.
So, because spiriway depends on both lakos ^2.0.5 and auto_route_generator ^10.0.1, version solving failed.

**Comment by OlegAlexander** [comment]
Hi @MichalNemec, would this work?

```
dependencies:
  path: ^1.9.1
  args: ^2.7.0
  directed_graph: ^0.4.5
  glob: ^2.1.3
  darq: ^2.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  string_scanner: ^1.4.1
  yaml: ^3.1.3
  pub_semver: ^2.2.0
```
